### PR TITLE
Hotfix

### PR DESCRIPTION
**Pull request by jupe**
merging fixes from master

**note:** unit tests is not working in release branch, just for note..

@tommikas @kjbracey-arm @yogpan01 @teetak01

### CODE REVIEW

**Comment by tommikas** [comment]
Should ARMmbed/mbed-trace#31 perhaps get in too? Although I'm not sure which builds it fixes exactly.

**Comment by kjbracey-arm** [comment]
Does it fix the library order problem?

**Comment by kjbracey-arm** [comment]
Hard to tell - no commit message.

**Comment by tommikas** [comment]
It doesn't seem to. I'm not sure what application and problem it fixes exactly. Asked Jaakko for elaboration but he's probably left the office by now.

**Comment by jupe** [comment]
I merged that #31 to master, but could it cause problems I'm not sure. Perhaps we shouldn't merge it to release branch

**Comment by jupe** [comment]
maybe we should merge this and update version #37 and do yotta publish, ok?

**Comment by teetak01** [comment]
Jaakko's fix would seem to work. Tested quickly.

**Comment by tommikas** [comment]
I take that back. It does seem to fix it.

**Comment by teetak01** [comment]
This is still missing Jaakko's fix?

**Comment by teetak01** [comment]
As in this alone will not fix the build issues.

**Comment by jupe** [comment]
now it's included in this PR -> going to release branch

**Comment by jupe** [comment]
ready to merge ?

**Comment by teetak01** [comment]
builds linux-example + linux-tests work fine with this.

**Pull request merged**
