### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by jupe**
follow release 1.1.2

* increase version number

@teetak01

### CODE REVIEW

**Comment by teetak01** [comment]
Why add the ignore test-folder to master? That breaks the tests. I think its enough if we have that in the release branch.

**Comment by jupe** [comment]
ups, I'll revert it

**Comment by teetak01** [comment]
LGTM, you are adding an old missing tag for 1.1.1? Next release will be 1.1.2

**Comment by jupe** [comment]
better?

**Comment by teetak01** [comment]
yep :+1:

**Comment by teetak01** [comment]
Probably need to merge the small recent fix from master to release also ( @tommikas )

FYI: This is currently a bit complicated. #Master-branch has the cpputest dependencies from a private ARM-repo, so we need to make releases without those components from seperate branch (so far it has been release-branch).

**Pull request merged**
