### PR TITLE
Add documentation on how to change trace level.

### PR DESCRIPTION
**Pull request by korjaa**
Also fixed an issue where MBED_TRACE_MAX_LEVEL would be ignored when mbed_vtracef() was called directly.

### CODE REVIEW

**Comment by korjaa** [comment]
Migrated from here https://github.com/ARMmbed/mbed-os/pull/8480

**Comment by jjaakola-arm** [comment]
Mbed Edge relies that `mbed_vtracef` does not obey trace levels:
https://github.com/ARMmbed/mbed-edge-internal/blob/0.6.x/edge-client/edge-client/edge_client_impl.h#L156-L163
There is a need to have some info logging regardless of generic log trace level.

**Comment by korjaa** [comment]
Oh boy.. :P

**Comment by korjaa** [comment]
I guess it kind of makes sense. I removed the check from mbed_vtracef() but left the MBED_TRACE_MAX_LEVEL flag to mbed_lib.json.

**Comment by korjaa** [comment]
Failing on

```
12:18:29 [Cobertura] Code coverage enforcement failed for the following metrics:
12:18:29 
12:18:29 [Cobertura]     Lines's stability is 90.74 and set mininum stability is 90.77.
12:18:29 
12:18:29 [Cobertura]     Conditionals's stability is 73.26 and set mininum stability is 73.56.
12:18:29 
12:18:29 [Cobertura] Setting Build to unstable.
```

**Comment by korjaa** [comment]
@jupe, flag name changed and added more documentation.

**Comment by jupe** [comment]
> @jupe, flag name changed and added more documentation.

ups, I meant that should add documentation to readme instead.. 🙄😁 maybe you could add some mentions about this flag there as well...

**Comment by korjaa** [comment]
Makes sense

**Comment by korjaa** [comment]
Added section to README.md about tracing level.

**Pull request merged**
