### PR TITLE
remove nsdynmemLIB.h usage case

### PR DESCRIPTION
**Pull request by teetak01**
@jupe @SeppoTakalo 

Is taking this out fine? Anything still depending on it?

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Only if we document that trace functions are NOT interrupt safe.
Actually.. they might have never been.

So I'm fine with the change.

**Comment by jupe** [comment]
but this pr is nothing to do with interrupt safe or is it? but yes, that should be mention in readme.

**Comment by SeppoTakalo** [comment]
`nsdynmem_alloc()` is interupt safe, but `malloc()` is not.

But same goes for `printf()` they are not interrupt safe either.

**Comment by jupe** [comment]
I see. Could you @teetak01 add mention (readme.md) that current implementation is not interrupt safe. We should add support for threads and interrupt safe functionality, but those not directly related to this PR so we can merge this..

**Comment by teetak01** [comment]
Ok, added mention to README.

**Pull request merged**
