### PR TITLE
remove EXCLUDE_FROM_ALL

### PR DESCRIPTION
**Pull request by teetak01**
@jupe @SeppoTakalo 

Unittests did not seem to be working properly. I took of the EXCLUDE_FROM_ALL flag and those started to run properly. Anything that might cause problems to other modules depending on mbed-trace?

### CODE REVIEW

**Comment by teetak01** [comment]
So the tests in CI has been working as they use "yt test mbed_trace_test". I was trying to run them as "yt test" which is the generic way to call on unittests. So in the sense this change is not very important especially if it might break something although mbed-client-cli has similar CMakeLists.txt configuration.

**Comment by jupe** [comment]
@SeppoTakalo do you know about this?

**Comment by SeppoTakalo** [comment]
I have no knowledge about this flag.

**Comment by teetak01** [comment]
Let's close this for now. Quite trivial issue in any case.

**Pull request closed without merging**
