### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by miklis**
fixes: IOTSYSTOOL-1021

### CODE REVIEW

**Comment by teetak01** [comment]
This should be updated and merged. @marhil01 @jupe @miklis

**Comment by teetak01** [comment]
Well, this needs to be rewritten. Its trying to build some non-existing unrelated component. It should build one of the example/test-applications.

**Comment by jupe** [comment]
we could reuse Jenkinsfile from here: https://github.com/ARMmbed/mbed-client-cli/blob/master/Jenkinsfile

**Comment by jupe** [comment]
Replaced with #87

**Pull request closed without merging**
